import React from 'react';
import ReactDOM from 'react-dom';
import './tailwind.css';
import App from './App';
import * as serviceWorker from './serviceWorker';
import { ReactQueryDevtools } from 'react-query-devtools'

localStorage.setItem("token","eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Im1xTFFXMDlNTUxRMUNNZGJpV3cwSyJ9.eyJodHRwczovL2hhc3VyYS5pby9qd3QvY2xhaW1zIjp7IngtaGFzdXJhLWRlZmF1bHQtcm9sZSI6InVzZXIiLCJ4LWhhc3VyYS1hbGxvd2VkLXJvbGVzIjpbInVzZXIiXSwieC1oYXN1cmEtdXNlci1pZCI6Imdvb2dsZS1vYXV0aDJ8MTAxMDY3MTY5MTU2MDA4MjE2OTE2In0sImdpdmVuX25hbWUiOiJBcnVuIGthcnRoaSIsImZhbWlseV9uYW1lIjoiTWFuaSIsIm5pY2tuYW1lIjoiZGV2bG9wZXIubWFrayIsIm5hbWUiOiJBcnVuIGthcnRoaSBNYW5pIiwicGljdHVyZSI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hLS9BT2gxNEdpVDVLMVhraUhzeUFnamVMaVRiVDVKNm5oZUhuMzhrTktfMUxieFdnIiwibG9jYWxlIjoiZW4tR0IiLCJ1cGRhdGVkX2F0IjoiMjAyMC0wNy0xMlQwMzoxNDowOC42MDFaIiwiaXNzIjoiaHR0cHM6Ly90ZXN0LTMyMy51cy5hdXRoMC5jb20vIiwic3ViIjoiZ29vZ2xlLW9hdXRoMnwxMDEwNjcxNjkxNTYwMDgyMTY5MTYiLCJhdWQiOiJNclVTM3NZTEpUU1paMzJpUjN4OUhwQWJ3MzlWVVJVaCIsImlhdCI6MTU5NDUyMzY0OCwiZXhwIjoxNTk0NTU5NjQ4LCJhdF9oYXNoIjoicThsaTdKX2xqWXhqZDZHRzVMd3JDQSIsIm5vbmNlIjoifkFEcHJHcnE1S1kwblNBcjFxMnpSUWtDbG54eGRnS1QifQ.LghsLG_PgGHk1ChXx73-jevX2VKVnGZycDkHCkwgQ3j3lPNYVjc2nGZbSw8EOf2gfPArtlMJ7On52w7w8VfOtGQ2BbOXHWgKHP3yhJ-i70AMoFykWVAC-b0WjVwMhofrs8FtErS05BnUC_PNd7QUVh-rhX_eh0cNDiWUfBcU8j-mqiiwZIhcWVDb4LWE4Q5BS-gemM0_EJq7pncZYgJvLLsHNoKK3wnTKHIHZQ2RRaBRsIYb6epnsjStwXAiD7kghzbQbwWy2PQd8wKXiEDYKi561fpOdivcOBkaVuWJsAeih7K6ekTfJxwOR3wakHSSmcB2erGrXcWfIk-qe27alA");
ReactDOM.render(
  <React.StrictMode>
    <App />
    <ReactQueryDevtools initialIsOpen />
  </React.StrictMode>,
  document.getElementById('root')
);

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: https://bit.ly/CRA-PWA
serviceWorker.unregister();
